[package]
name = "adb_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
clap = { version = "4.5.1", features = ["derive"] }
anyhow = "1.0.79"
thiserror = "1.0.56"
